import Link from "next/link";
import { notFound } from "next/navigation";
import { recapRepo } from "@/repositories/recap-repo";
import { RecapView } from "@/components/recap/recap-view";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Trophy, ArrowRight } from "lucide-react";
import type { Metadata } from "next";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ shareId: string }>;
}): Promise<Metadata> {
  const { shareId } = await params;
  const recap = await recapRepo.findByShareId(shareId);
  if (!recap) return { title: "Shared Recap" };
  return {
    title: recap.title,
    description: recap.summary ?? `Watch ${recap.title} — an AI-generated World Cup recap.`,
    openGraph: {
      title: recap.title,
      description: recap.summary ?? undefined,
      url: `${APP_URL}/share/${shareId}`,
      type: "video.other",
      ...(recap.thumbnailUrl
        ? { images: [{ url: `${APP_URL}${recap.thumbnailUrl}` }] }
        : {}),
    },
  };
}

export default async function SharePage({
  params,
}: {
  params: Promise<{ shareId: string }>;
}) {
  const { shareId } = await params;
  const recap = await recapRepo.findByShareId(shareId);
  if (!recap || !recap.isPublic || recap.status !== "COMPLETED") notFound();

  return (
    <main className="mx-auto flex w-full max-w-6xl flex-col gap-6 px-4 py-8 sm:px-6">
      <header className="flex flex-wrap items-center justify-between gap-4">
        <Link href="/" className="flex items-center gap-2 font-bold tracking-tight">
          <Trophy className="size-5 text-accent" aria-hidden />
          WC Recap<span className="text-accent">.ai</span>
        </Link>
        <div className="flex items-center gap-3">
          <Badge variant="secondary">Shared recap</Badge>
          <Button size="sm" asChild>
            <Link href="/create">
              Make your own <ArrowRight aria-hidden />
            </Link>
          </Button>
        </div>
      </header>
      <RecapView recap={recap} />
      <footer className="border-t border-border py-6 text-center text-sm text-muted">
        Generated by the AI World Cup Recap Generator —{" "}
        <Link href="/" className="text-accent underline-offset-4 hover:underline">
          create yours
        </Link>
      </footer>
    </main>
  );
}
