import type {
  AiRecapOutput,
  RecapContext,
  RecapPreferences,
  ScoredMoment,
  VideoSlide,
} from "@/types";
import { STAGE_LABELS } from "@/lib/utils";

const TARGET_SECONDS: Record<string, number> = {
  SHORT: 60,
  STANDARD: 115,
  EXTENDED: 260,
};

const CAPS: Record<string, { matches: number; moments: number }> = {
  SHORT: { matches: 4, moments: 2 },
  STANDARD: { matches: 7, moments: 3 },
  EXTENDED: { matches: 10, moments: 5 },
};

/**
 * Converts the recap content into a storyboard of VideoSlides, scaled
 * to hit the requested duration. This is the "director" of the video.
 */
export function buildTimeline(
  ctx: RecapContext,
  prefs: RecapPreferences,
  story: AiRecapOutput,
  moments: ScoredMoment[],
): VideoSlide[] {
  const caps = CAPS[prefs.duration] ?? CAPS.STANDARD;
  const subject = ctx.focusTeam ?? ctx.focusPlayer?.team ?? null;
  const accent = subject?.accentColor ?? "#f59e0b";

  const slides: VideoSlide[] = [];

  slides.push({
    kind: "intro",
    durationSec: 4,
    title: ctx.tournament.name.toUpperCase(),
    subtitle: "A personalized recap, generated by AI",
    accent,
  });

  slides.push({
    kind: "subject",
    durationSec: 7,
    title: ctx.focusPlayer
      ? ctx.focusPlayer.name
      : (ctx.focusTeam?.name ?? ctx.tournament.name),
    subtitle: ctx.focusPlayer
      ? `${ctx.focusPlayer.team.name} · ${ctx.focusPlayer.position}`
      : `FIFA ranking ${ctx.focusTeam?.fifaRanking ?? "—"} · ${ctx.tournament.name}`,
    body: ctx.teamStats
      ? [
          `${ctx.teamStats.played} matches · ${ctx.teamStats.won}W ${ctx.teamStats.drawn}D ${ctx.teamStats.lost}L`,
          `Best finish: ${ctx.teamStats.bestFinish}`,
        ]
      : undefined,
    code:
      ctx.focusTeam?.shortName ??
      ctx.focusPlayer?.team.shortName ??
      undefined,
    accent,
  });

  const journeyMatches = ctx.matches.slice(0, caps.matches);
  for (const m of journeyMatches) {
    slides.push({
      kind: "match",
      durationSec: 6,
      title: STAGE_LABELS[m.stage].toUpperCase(),
      subtitle: m.venue,
      match: {
        home: `${m.homeTeam.name} (${m.homeTeam.shortName})`,
        away: `${m.awayTeam.name} (${m.awayTeam.shortName})`,
        score: `${m.homeScore} – ${m.awayScore}${
          m.homePenalties != null
            ? ` · pens ${m.homePenalties}–${m.awayPenalties}`
            : ""
        }`,
        stage: STAGE_LABELS[m.stage],
        venue: m.venue,
      },
      accent,
    });
  }

  for (const moment of moments.slice(0, caps.moments)) {
    slides.push({
      kind: "moment",
      durationSec: 6,
      title: moment.title,
      subtitle: `${moment.scoreline}${moment.minute != null ? ` · ${moment.minute}'` : ""}`,
      body: [moment.description],
      accent,
    });
  }

  const topPlayer = story.keyPlayers[0];
  if (topPlayer) {
    const stat = ctx.playerStats.find((p) => p.player.name === topPlayer.name);
    slides.push({
      kind: "player",
      durationSec: 6,
      title: topPlayer.name,
      subtitle: "Player of the recap",
      body: [
        topPlayer.note,
        ...(stat
          ? [
              `${stat.goals} goals · ${stat.assists} assists · ${stat.avgRating.toFixed(1)} rating`,
            ]
          : []),
      ],
      accent,
    });
  }

  slides.push({
    kind: "stats",
    durationSec: 7,
    title: "BY THE NUMBERS",
    statLines: story.statisticsHighlights.slice(0, 5),
    accent,
  });

  slides.push({
    kind: "verdict",
    durationSec: 7,
    title: "FINAL VERDICT",
    body: [story.finalVerdict],
    accent,
  });

  slides.push({
    kind: "outro",
    durationSec: 4,
    title: story.title,
    subtitle: "Generated with AI World Cup Recap Generator",
    accent,
  });

  // Scale slide durations to hit the target length (transition overhead
  // shaves ~0.5s per boundary — accounted for by padding the target).
  const target = TARGET_SECONDS[prefs.duration] ?? TARGET_SECONDS.STANDARD;
  const base = slides.reduce((s, x) => s + x.durationSec, 0);
  const factor = (target + slides.length * 0.5) / base;
  for (const s of slides) {
    if (s.kind === "intro" || s.kind === "outro") continue; // keep bookends tight
    s.durationSec = Math.max(3.5, Math.round(s.durationSec * factor * 2) / 2);
  }

  return slides;
}
